name: hello world 
on: workflow_dispatch
jobs:
  build:
    runs-on: ubunto-latest 
    steps: 
      - name: build steps
      - run: echo "a demo build"
 test:
   runs-on: ubunto-latest
   steps: 
     - name: test phase 
       run: echo "running test cases"
  deploy:
   runs-on: ubuntu-latest 
   steps: 
     - name: deploy the app 
       run: echo "deploying the app"
   
